### ISSUE TITLE
Script fails if environment variable LANG=de_DE.UTF-8

### ISSUE THREAD

**Issue by mheene** [shellspec/shellmetrics#4]
Testcase 1:

LANG=de_DE.UTF-8

script fails:
`==============================================================================`
 NLOC    NLOC  LLOC    LLOC    CCN Func File (lines:comment:blank)
total     avg total     avg    avg  cnt
`------------------------------------------------------------------------------`
/home/markus/bin/shellmetrics: Zeile 356: printf: 13.2083: Ungültige Zahl.
/home/markus/bin/shellmetrics: Zeile 356: printf: 9.29167: Ungültige Zahl.
/home/markus/bin/shellmetrics: Zeile 356: printf: 2.625: Ungültige Zahl.

Testcase 2:
export LANG=en

script is sucessful:
`==============================================================================`
 NLOC    NLOC  LLOC    LLOC    CCN Func File (lines:comment:blank)
total     avg total     avg    avg  cnt
`------------------------------------------------------------------------------`
  317   13.21   223    9.29   2.62   24 helper.sh (418:38:63)
`------------------------------------------------------------------------------`

works fine

**Comment by ko1nksm** [comment]
I fixed it so that it works for now. However, contrary to your locale, the decimal separator will be output as `.` instead of `,`. This is a development tool, so I don't think a problem with it, but should I use `,` for something like this?

**Comment by mheene** [comment]
Perfect, thanks again for your swift action. I'm fine with `.` instead of `,`.
